### ISSUE TITLE
Cannot Connect to blheli_s?

### ISSUE THREAD

**Issue by ahalekelly** [BrushlessPower/BlHeli-Passthrough#4]
Hey, I'm having trouble getting this to work. I'm using BLHeli_s ESCs, which I don't see mentioned as supported, but if you're doing passthrough they should be the same right? I tried both an ESP32 with CP210x and an Arduino Nano with CH340. Arduino version is 1.8.12

The Arduino Nano works with the blheli 4 way firmware, so I know the arduino and drivers are good. I followed all the instructions in the readme. When I hit connect in BLHeliSuite, I get the error `Connect to Flightcontroler failed!` ESC-Configurator.com is also not able to connect.

The ESP-32 I am able to connect, but it throws the error `Failed to set interface to appropriate mode!`. If I hit Read Setup, it is able to detect that there is an ESC connected, but cannot read the firmware version or any details. In ESC-Configurator.com, I am similarly able to connect but not read any ESC data. Here's the log:

```2022/02/08 05:09:16: Plugged in
2022/02/08 05:10:12: Port selected
2022/02/08 05:10:13: Opened serial port
2022/02/08 05:10:14: MSP command failed: Timed out after 1000ms
2022/02/08 05:10:14: Port already in use by another application - try re-connecting
2022/02/08 05:10:14: TX: cmd_InterfaceExit - 0x0 
2022/02/08 05:10:49: Opened serial port
2022/02/08 05:10:49: MultiWii API version received: 1.42.0
2022/02/08 05:10:49: Flight controller info, identifier: BTFL version: 4.1.0
2022/02/08 05:10:49: Running firmware released on:  
2022/02/08 05:10:49: Board: BPMC, version: 0
2022/02/08 05:10:49: Unique device ID received - 0x0000
2022/02/08 05:10:51: MSP command failed: Timed out after 1000ms
...
2022/02/08 05:10:57: MSP command failed: Timed out after 1000ms
2022/02/08 05:10:59: Trying to read 1 ESCs
2022/02/08 05:10:59: TX: cmd_DeviceInitFlash - 0x0 
2022/02/08 05:10:59: Failed processing command cmd_DeviceInitFlash after 0 retries. 
2022/02/08 05:10:59: Failed reading ESC 1
2022/02/08 05:10:59: Error: Message not OK 
```

Any ideas? I'll give BLHeli_32 ESCs a try when they arrive.

**Comment by ericlangel** [comment]
hi,
the Atmega Firmware is a little bit older (more bugs) then ESP32. Thats the reason why you cant connect with atmega

But, thats not the Point.
BlHeli_s with Silabs MCU is a complete different protocol.
This library just works with imARM_BLB protocol (BlHeli_32 and AM32)

**Comment by ahalekelly** [comment]
Ah okay. Thank you for the quick reply!

**Comment by ahalekelly** [comment]
Would be good to put this info in the readme
