### ISSUE TITLE
RP2040 porting issues

### ISSUE THREAD

**Issue by bastian2001** [BrushlessPower/BlHeli-Passthrough#9]
I am trying to port the ESP code (minus BLE) over to an RP2040 so I can configure ESCs through my own FC. I am using the Programmable IO hardware of the RP2040. I wrote some code (pioWrite, pioRead and pioEnableTX) to make the pin do proper halfduplex UART at 19200 Baud. I verified my code works correct within a basic Serial passthrough, but when I use the same functions in SendESC and GetESC, I cannot get any response from the ESC. Is there anything special about the halfduplex serial? I am getting an "unkwown error" by BLHeliSuite32 when I try to read the settings from the ESC (connecting works well):
![grafik](https://github.com/BrushlessPower/BlHeli-Passthrough/assets/25935728/e5100203-fb39-4d45-a266-14de2f177863)
![grafik](https://github.com/BrushlessPower/BlHeli-Passthrough/assets/25935728/c8f3d140-da60-4cf1-93e9-4bbe44942cba)

**Comment by bastian2001** [comment]
A lot of debugging later, and I fixed it. Haven't thoroughly tested it, but it was a simple fix: I had somehow changed an int from 16 to 8 bit and was wondering why it did not reach 264, though there was likely another thing that I don't remember because the error in the screenshot was not the error I was fighting with anymore later...

I will prepare a PR in the coming days with the RP2040 port, if you are interested.

**Comment by ericlangel** [comment]
if you have a PR  i will merge it.

N2K that this repo is still used and working.

**Comment by bastian2001** [comment]
@ericlangel I submitted a PR with some changes to allow for multiple ESCs

**Comment by ericlangel** [comment]
@bastian2001 thank you for your PR. i merged it to the Repo so everyone can use it for RP2040
